# ---------------------------------------------------------------------------- #
#                                                                              #
#                          Calender Events config                              #
#                                                                              #
# ---------------------------------------------------------------------------- #

# All times int this configuration file are interpreted in the timezone of your server

# the following events are examples for you to understand how to add custom events with this plugin.
# To let the plugin do something on these events, go to the section 'listener'.
# For more complex action on events, use the API.
# Please visit www.spigotmc.org/resources/35536/ for more information on the API.
events:
  # The event label needs to be unique and is used as its identifier in the 'listener' section
  newMonth:
    timing:
      # This will get called on every first of the month.
      # A date with just two numbers is interpreted as any such day in any month.
      # You can add more dates to the '01' just put a ',' in between (e.g. "01,05,25")
      occasion: "01"
      # 24h format! Event gets called in the first second of the given minute.
      # Each day goes from 00:00 to 23:59 ;)
      time: "00:00"

  # Event called on the first of every week
  newWeek:
    timing:
      occasion: "monday"
      time: "00:00"

  # Event called on the first and second of every year
  newYearAndSecond:
    timing:
      # A date without a year gets called every year
      occasion: "01.01, 02.01"
      time: "00:00"

  # Event fired on christmas 2022
  christmas2022:
    timing:
      occasion: "24.12.2022"
      time: "12:00"

  # Event called every day, every two hours
  everyDayEveryTwoHours:
    timing:
      # 'every day' gets translated to 'monday, tuesday, wednesday, thursday, friday, saturday, sunday'
      occasion: "every day"
      time: "01:00,03:00,05:00,07:00,09:00,11:00,13:00,15:00,17:00,19:00,21:00,23:00"

  # Event called every working/school day, every hour
  workingDaysEveryHour:
    timing:
      occasion: "monday, tuesday, wednesday, thursday, friday"
      # use the placeholder 'x' to stand for any possible number
      time: "xx:00"


  # COMBINED EVENTS
  #  combined events can be used to create special scheduling like e.g. every first sunday of a month
  #  combined events contain a list of "normal" calendar event labels and are only fired when ALL of the listed events are fired

  # lets create some normal events to use in a combined event
  sunday: # every sunday
    timing:
      occasion: "sunday"
      time: "12:00" # SAME TIME AS THE OTHER EVENT BELOW (IMPORTANT)
  firstWeekOfMonth: # every day of the first week in a month
    timing:
      occasion: "01, 02, 03, 04, 05, 06, 07"
      time: "12:00"

  # this event will fire on every first sunday in a month at 12:00
  firstSundayInMonth:
    events: # lables of the two "normal" events above
      - "sunday"
      - "firstWeekOfMonth"


# General Calendar Events settings
settings:
  # If your server is in a different timezone than the timezone you would like your events to be triggered in, you can configure the difference in hours here.
  # Example:
  #     Server:   UTC
  #     Players:  UTC +1
  #     configure offsetHours = 1
  #     The events above will trigger at the configured times for your UTC +1 players
  #     This setting supports negative values (e.g. -2 for Server UTC+2 and players UTC)
  offsetHours: 0
  # The locale defines the month and day names in the event (%day%, %month%).
  # Use an IETF language tag (see: https://r12a.github.io/app-subtags/).
  language: "en"


# You can use the listener for basic actions such as
# sending commands, actionbars, broadcasts and titles

# use & for colors
# %time% will be replaced with the events time (24h format hh:mm)
# %day% will be replaced with the name of the day in the locale defined at 'settings.locale'
# %month% will be replaced with the name of the month in the locale defined at 'settings.locale'
listener:
  workingDaysEveryHour:
    # %allOnline%    --->  this gets called for every online player and will be replaced with the player name
    # %allOffline%   --->  this gets called for every offline player and will be replaced with the player name
    # %allPlayers%   --->  this gets called for every player (online and offline) and will be replaced with the player name
    commands:
    # - "tell %allOnline% &4Hey there %allOnline% &1:)"

    # all commands in this section will run for EVERY player that has the given permission
    commandsWithPerm:
      # for every unique key commands and perm have to be defined
      example:
        # list of commands.
        #     %player% is replaced by the player name
        #     %allOnline% is replaced by the player name
        #     %perm% is replaced by the permission
        commands:
          - "tell %player% &4Hey there %player% &1You have the permission %perm%"
        # the commands above are only dispatched for the player, if he has the defined permission
        perm: "example.perm"

    # Broadcast to everyone
    #broadcast: "[Server] &1Hello everyone! Enjoy the game :)"

    broadcastWithPerm:
      perm: "example.perm"
      broadcast: "Hey man, you got a special permission!"

    # %player% will be replaced with the players name
    actionbar:
      # Permission is optional. If empty, the actionbar will be send to everyone
      perm: "example.perm"
      bar: "&1That's a cool actionbar, %player% &r(btw: it's %time%)"

    # %player% will be replaced with the players name
    title:
      # perm is optional. If empty, the title will be send to everyone
      perm: "example.perm"
      title: "&1Hi there %player%"
      subTitle: "It's now &4%time%&r!"
      # ticks (20 = 1s) the title is visible (default 10). 10 ticks fading-in and 10 ticks fading-out are hardcoded!
      ticksToDisplay: 20

  newMonth:
    #broadcast: "It is now &1%month%"

# CalendarEvents is on bStats: https://bstats.org/plugin/bukkit/CalendarEvents
# If you don't want any anonymous data to be send, you can opt it out here.
bstats:
  # Please consider leaving this enabled.
  # Having statistics helps me to see in which projects/features I should invest more time.
  disabled: false
